DROP DATABASE IF EXISTS roadtrip_db;
CREATE DATABASE roadtrip_db;
USE roadtrip_db;

CREATE TABLE roadTrip(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  states INTEGER(255),
  city VARCHAR(255),
  activities VARCHAR(255),
  vibeType VARCHAR(255),
  restStop VARCHAR(255),
);

CREATE TABLE states(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  states VARCHAR(255),
  PRIMARY KEY (id)
);

 CREATE TABLE city(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  states VARCHAR(255),
  PRIMARY KEY (id)
 );

CREATE TABLE activities(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  activities VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE vibeType(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  vibeType VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE restStop(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  states VARCHAR(255),
  city VARCHAR(255),
  PRIMARY KEY (id)
);