DROP DATABASE IF EXISTS roadtrip_db;
CREATE DATABASE roadtrp_db;
USE roadtrip_db;


CREATE TABLE States(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  States VARCHAR(255),
  PRIMARY KEY (id)
);

 CREATE TABLE city(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  stateId INTEGER(255),
  city VARCHAR(255),
  FOREIGN KEY (statesid) REFERENCES states(id)
 );

CREATE TABLE Activities(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  States VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE vibe_type(
  id INTEGER(255) AUTO_INCREMENT NOT NULL,
  States VARCHAR(255),
  PRIMARY KEY (id)
);


